### ISSUE TITLE
friendda.org is dead

### ISSUE THREAD

**Issue by tedder** [rands/friendda#1]
Looks like the domain is still registered but DNS isn't configured.

**Comment by fergbrain** [comment]
Works for me...
![frienda](https://cloud.githubusercontent.com/assets/1291387/13861562/3087d904-ec4b-11e5-9b36-19295a17cbfa.png)

**Comment by tedder** [comment]
Yeah, appears to work now. Maybe it didn't, or maybe it was just me.

```
host friendda.org
friendda.org has address 64.13.232.146
friendda.org mail is handled by 10 mail.friendda.org.
```
